server:
  port: 80

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://175.24.51.62:3306/newborn?serverTimezone=GMT%2B8 # 数据库名称
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动包
  dbcp2:
    min-idle: 5 # 数据库连接池的最小维持连接数
    initial-size: 5 # 初始化连接数
    max-total: 5 # 最大连接数
    max-wait-millis: 150 # 等待连接获取的最大超时时间
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html

